export const headerNav = {
  Home: '/',
  Projects: '/projects',
  Products: '/products',
  Articles: '/articles',
  Authors: '/authors',
};

export const postsList = [
  {
    id: 1,
    title: '15 полезных однострочных выражений JavaScript',
    description:
      'Улучшение JavaScript-кода за пару минут перевод 15 Helpful JavaScript One-Liners',
    image:
      'https://external-content.duckduckgo.com/iu/?u=http%3A%2F%2Fintehweb.ru%2Fassets%2Fimg%2Fblog%2Fdesign-line%2Fpic-29.png&f=1&nofb=1',
    authorId: 1,
  },
  {
    id: 2,
    title: 'Полиморфизм простыми словами',
    description:
      'Скорее всего вы уже встречались с понятием “полиморфизм” и даже помните примеры с наследованием, но они показывают далеко не всё',
    image:
      'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fi.stack.imgur.com%2FlzwOQ.png&f=1&nofb=1',
    authorId: 1,
  },
  {
    id: 3,
    title:
      'Нейросети с нуля для JavaScript разработчиков (Часть 1: Перцептрон)',
    description:
      'Перевод статьи Elyx0: Neural networks from scratch for Javascript linguists (Part1 The Perceptron)',
    image:
      'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fi.pinimg.com%2Foriginals%2Fd3%2Fbf%2Fb8%2Fd3bfb823feef852bc11f4c46001fe7dd.png&f=1&nofb=1',
    authorId: 5,
  },
  {
    id: 4,
    title: '8 практичных хитростей веб-разработчика применить немедленно!',
    description:
      'HTML, CSS и JS хинты, которые полезно знать перевод 8 Tricks for Web Developers You Can Put Into Practice Immediately',
    image:
      'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fcamper-c.ru%2F800%2F600%2Fhttps%2Fbiznesbooks.com%2Fcomponents%2Fcom_jshopping%2Ffiles%2Fimg_products%2F583e844167dc9.jpg&f=1&nofb=1',
    authorId: 2,
  },
  {
    id: 5,
    title: 'Насколько JavaScript сильный?',
    description:
      'Погружение в тему неявных преобразований. Где и как возникают и вычисляются неявные преобразования в JavaScript?',
    image:
      'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fimg03.rl0.ru%2Fafisha%2Fe1200x630i%2Fdaily.afisha.ru%2Fuploads%2Fimages%2F6%2F25%2F625f254ec12554a4851e95ffa871e7bc.png&f=1&nofb=1',
    authorId: 3,
  },
  {
    id: 6,
    title: 'Изучите CSS-переменные за 5 минут',
    description:
      'Перевод статьи Per Harald Borgen: Learn CSS Variables in 5 minutes',
    image:
      'https://external-content.duckduckgo.com/iu/?u=http%3A%2F%2Fjem-space.ru%2Fcontent%2Fimages%2F2018%2F02%2Fcss.jpg&f=1&nofb=1',
    authorId: 3,
  },
  {
    id: 7,
    title: 'Создание MEVN-приложения (Часть 1/2)',
    description:
      'Создание full-stack приложения на основе Vue.js и Express.js (+MongoDB)',
    image:
      'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fcdn-images-1.medium.com%2Fmax%2F1600%2F1*yA_FlNx_ynRi2ok7dmfoIQ.png&f=1&nofb=1',
    authorId: 3,
  },
  {
    id: 8,
    title: 'Реактивность Vue.js',
    description:
      'Реактивность фреймворка Vue.js и использование метода Vue.set',
    image:
      'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fi.ytimg.com%2Fvi%2FLV235z6qOUI%2Fmaxresdefault.jpg&f=1&nofb=1',
    authorId: 4,
  },
  {
    id: 9,
    title: 'Микроптимизации производительности и JavaScript',
    description:
      'Недавно в комментариях на Hexlet я поучаствовал в дискуссии на тему «Что важнее — оптимизации производительности или качество кода?» Если…',
    image:
      'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fitvdn.blob.core.windows.net%2Fcatalog-images%2Fjs-apps-optimization-img.jpg&f=1&nofb=1',
    authorId: 4,
  },
  {
    id: 10,
    title: 'Девшахта-подкаст',
    description:
      '#108: Производительность кода — это важнейший критерий качества?',
    image:
      'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fres.cloudinary.com%2Fteepublic%2Fimage%2Fprivate%2Fs--HGX34F_2--%2Ft_Preview%2Fb_rgb%3Affb81c%2Cc_lpad%2Cf_jpg%2Ch_630%2Cq_90%2Cw_1200%2Fv1539273850%2Fproduction%2Fdesigns%2F3302095_0.jpg&f=1&nofb=1',
    authorId: 5,
  },
  {
    id: 11,
    title: 'Одна из самых красивых идей в информатике: Y-Combinator',
    description:
      'Перевод статьи Lucas Fernandes da Costa “Y: The Most Beautiful Idea in Computer Science explained in JavaScript”',
    image:
      'https://external-content.duckduckgo.com/iu/?u=http%3A%2F%2Fatlantablackstar.com%2Fwp-content%2Fuploads%2F2014%2F02%2Fy-combinator-600x240.jpg&f=1&nofb=1',
    authorId: 5,
  },
  {
    id: 12,
    title: 'Начало работы с Node.js',
    description: 'Node Hero: Глава 1',
    image:
      'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fitvdn.blob.core.windows.net%2Farticles-new%2F890e2840-8a78-46f9-b78e-360b8bd2e96a-cover.jpg&f=1&nofb=1',
    authorId: 5,
  },
];

export const authors = [
  {
    id: 1,
    name: 'Dodik',
    description: "Author's biography",
    photo:
      'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftheviraler.com%2Fwp-content%2Fuploads%2F2020%2F02%2Ffunny-weird-people-01-2.jpg&f=1&nofb=1',
  },
  {
    id: 2,
    name: 'Narco',
    description: "Author's biography",
    photo:
      'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fwww.funmag.org%2Fwp-content%2Fuploads%2F2014%2F10%2Ffunny-looking-people-16-photos-16.jpg&f=1&nofb=1',
  },
  {
    id: 3,
    name: 'Fool',
    description: "Author's biography",
    photo:
      'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fmojly.com%2Fwp-content%2Fuploads%2F2017%2F12%2Fweird-laughing-people-funny-pics-images-mojly-photos-maxresdefault-001.jpg&f=1&nofb=1',
  },
  {
    id: 4,
    name: 'Old Freak',
    description: "Author's biography",
    photo:
      'https://external-content.duckduckgo.com/iu/?u=http%3A%2F%2F2.bp.blogspot.com%2F-5Za36LEzgZw%2FUPPdUa3G8_I%2FAAAAAAAAB78%2Folw098-Yres%2Fs1600%2FFunny%2BUgly%2BPeople_7.jpg&f=1&nofb=1',
  },
  {
    id: 5,
    name: 'Dog-man',
    description: "Author's biography",
    photo:
      'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fi.ytimg.com%2Fvi%2FG6O3m4x-ONc%2Fmaxresdefault.jpg&f=1&nofb=1',
  },
];

export const goodsAssets = {
  colors: {
    white: 'white',
    black: 'black',
    purple: 'purple',
    grey: 'grey',
    blue: 'blue',
    gold: 'gold',
    green: 'green',
    red: 'red',
    pink: 'pink',
  },
  countries: {
    usa: 'USA',
    korea: 'Korea',
    china: 'China',
    japan: 'Japan',
  },
  OS: {
    android: 'Android',
    ios: 'iOS',
  },
};

export const goods = [
  {
    brand: 'Samsung',
    model: 'Galaxy M52',
    memory: 128,
    price: 12999,
    haveDiscount: true,
    isStoredInFacility: true,
    color: goodsAssets.colors.black,
    country: goodsAssets.countries.korea,
    os: goodsAssets.OS.android,
    photo: 'https://content.rozetka.com.ua/goods/images/big/225753307.jpg',
  },
  {
    brand: 'Apple',
    model: 'iPhone 11',
    memory: 64,
    price: 19999,
    haveDiscount: false,
    isStoredInFacility: true,
    color: goodsAssets.colors.purple,
    country: goodsAssets.countries.usa,
    os: goodsAssets.OS.ios,
    photo: 'https://content2.rozetka.com.ua/goods/images/big/37393876.jpg',
  },
  {
    brand: 'Xiaomi',
    model: 'Redmi Note 10S',
    memory: 64,
    price: 8999,
    haveDiscount: true,
    isStoredInFacility: true,
    color: goodsAssets.colors.grey,
    country: goodsAssets.countries.china,
    os: goodsAssets.OS.android,
    photo: 'https://content1.rozetka.com.ua/goods/images/big/179450853.jpg',
  },
  {
    brand: 'Apple',
    model: 'iPhone 13',
    memory: 256,
    price: 33999,
    haveDiscount: false,
    isStoredInFacility: true,
    color: goodsAssets.colors.red,
    country: goodsAssets.countries.usa,
    os: goodsAssets.OS.ios,
    photo: 'https://content2.rozetka.com.ua/goods/images/big/221212843.jpg',
  },
  {
    brand: 'Samsung',
    model: 'Galaxy A52',
    memory: 128,
    price: 10999,
    haveDiscount: true,
    isStoredInFacility: false,
    color: goodsAssets.colors.blue,
    country: goodsAssets.countries.korea,
    os: goodsAssets.OS.android,
    photo: 'https://content2.rozetka.com.ua/goods/images/big/166279502.jpg',
  },
  {
    brand: 'Apple',
    model: 'iPhone 13 mini',
    memory: 512,
    price: 35999,
    haveDiscount: true,
    isStoredInFacility: true,
    color: goodsAssets.colors.green,
    country: goodsAssets.countries.usa,
    os: goodsAssets.OS.ios,
    photo: 'https://content2.rozetka.com.ua/goods/images/big/221273383.jpg',
  },
  {
    brand: 'Xiaomi',
    model: 'Redmi Note 11',
    memory: 128,
    price: 8499,
    haveDiscount: false,
    isStoredInFacility: false,
    color: goodsAssets.colors.grey,
    country: goodsAssets.countries.china,
    os: goodsAssets.OS.android,
    photo: 'https://content.rozetka.com.ua/goods/images/big/250762458.jpg',
  },
  {
    brand: 'Samsung',
    model: 'Galaxy M12',
    memory: 64,
    price: 6499,
    haveDiscount: true,
    isStoredInFacility: true,
    color: goodsAssets.colors.white,
    country: goodsAssets.countries.korea,
    os: goodsAssets.OS.android,
    photo: 'https://content1.rozetka.com.ua/goods/images/big/175471717.jpg',
  },
  {
    brand: 'Samsung',
    model: 'Galaxy A32',
    memory: 128,
    price: 9499,
    haveDiscount: true,
    isStoredInFacility: true,
    color: goodsAssets.colors.purple,
    country: goodsAssets.countries.korea,
    os: goodsAssets.OS.android,
    photo: 'https://content1.rozetka.com.ua/goods/images/big/165917377.jpg',
  },
  {
    brand: 'Samsung',
    model: 'Galaxy M52',
    memory: 128,
    price: 12999,
    haveDiscount: true,
    isStoredInFacility: true,
    color: goodsAssets.colors.green,
    country: goodsAssets.countries.korea,
    os: goodsAssets.OS.android,
    photo: 'https://content.rozetka.com.ua/goods/images/big/225753307.jpg',
  },
  {
    brand: 'Apple',
    model: 'iPhone 13 Pro Max',
    memory: 128,
    price: 43999,
    haveDiscount: true,
    isStoredInFacility: true,
    color: goodsAssets.colors.gold,
    country: goodsAssets.countries.usa,
    os: goodsAssets.OS.ios,
    photo: 'https://content2.rozetka.com.ua/goods/images/big/221216158.jpg',
  },
  {
    brand: 'Apple',
    model: 'iPhone 12',
    memory: 64,
    price: 24999,
    haveDiscount: false,
    isStoredInFacility: true,
    color: goodsAssets.colors.green,
    country: goodsAssets.countries.usa,
    os: goodsAssets.OS.ios,
    photo: 'https://content.rozetka.com.ua/goods/images/big/173867780.jpg',
  },
  {
    brand: 'Sony',
    model: 'Xperia 1 III',
    memory: 512,
    price: 39999,
    haveDiscount: false,
    isStoredInFacility: true,
    color: goodsAssets.colors.black,
    country: goodsAssets.countries.japan,
    os: goodsAssets.OS.android,
    photo: 'https://content1.rozetka.com.ua/goods/images/big/215587054.jpg',
  },
  {
    brand: 'Sony',
    model: 'Xperia 1 III',
    memory: 512,
    price: 39999,
    haveDiscount: false,
    isStoredInFacility: true,
    color: goodsAssets.colors.gold,
    country: goodsAssets.countries.japan,
    os: goodsAssets.OS.android,
    photo: 'https://content1.rozetka.com.ua/goods/images/big/215587054.jpg',
  },
  {
    brand: 'Apple',
    model: 'iPhone 12',
    memory: 64,
    price: 24999,
    haveDiscount: false,
    isStoredInFacility: true,
    color: goodsAssets.colors.purple,
    country: goodsAssets.countries.usa,
    os: goodsAssets.OS.ios,
    photo: 'https://content.rozetka.com.ua/goods/images/big/173867780.jpg',
  },
  {
    brand: 'Samsung',
    model: 'Galaxy M12',
    memory: 64,
    price: 6499,
    haveDiscount: true,
    isStoredInFacility: true,
    color: goodsAssets.colors.black,
    country: goodsAssets.countries.korea,
    os: goodsAssets.OS.android,
    photo: 'https://content1.rozetka.com.ua/goods/images/big/175471717.jpg',
  },
  {
    brand: 'Motorola',
    model: 'Moto G60',
    memory: 128,
    price: 8999,
    haveDiscount: true,
    isStoredInFacility: true,
    color: goodsAssets.colors.grey,
    country: goodsAssets.countries.usa,
    os: goodsAssets.OS.android,
    photo: 'https://content2.rozetka.com.ua/goods/images/big/220713124.jpg',
  },
  {
    brand: 'Apple',
    model: 'iPhone 13 mini',
    memory: 512,
    price: 35999,
    haveDiscount: true,
    isStoredInFacility: true,
    color: goodsAssets.colors.red,
    country: goodsAssets.countries.usa,
    os: goodsAssets.OS.ios,
    photo: 'https://content2.rozetka.com.ua/goods/images/big/221273383.jpg',
  },
  {
    brand: 'Apple',
    model: 'iPhone 13',
    memory: 256,
    price: 33999,
    haveDiscount: false,
    isStoredInFacility: true,
    color: goodsAssets.colors.black,
    country: goodsAssets.countries.usa,
    os: goodsAssets.OS.ios,
    photo: 'https://content2.rozetka.com.ua/goods/images/big/221212843.jpg',
  },
  {
    brand: 'Apple',
    model: 'iPhone 12',
    memory: 128,
    price: 27999,
    haveDiscount: false,
    isStoredInFacility: true,
    color: goodsAssets.colors.purple,
    country: goodsAssets.countries.usa,
    os: goodsAssets.OS.ios,
    photo: 'https://content.rozetka.com.ua/goods/images/big/175435401.jpg',
  },
  {
    brand: 'Apple',
    model: 'iPhone 13',
    memory: 128,
    price: 29999,
    haveDiscount: false,
    isStoredInFacility: true,
    color: goodsAssets.colors.pink,
    country: goodsAssets.countries.usa,
    os: goodsAssets.OS.ios,
    photo: 'https://content.rozetka.com.ua/goods/images/big/221214152.jpg',
  },
  {
    brand: 'Apple',
    model: 'iPhone 13 mini',
    memory: 128,
    price: 25999,
    haveDiscount: true,
    isStoredInFacility: true,
    color: goodsAssets.colors.pink,
    country: goodsAssets.countries.usa,
    os: goodsAssets.OS.ios,
    photo: 'https://content2.rozetka.com.ua/goods/images/big/221268401.jpg',
  },
  {
    brand: 'Apple',
    model: 'iPhone 13 Pro Max',
    memory: 256,
    price: 48999,
    haveDiscount: false,
    isStoredInFacility: true,
    color: goodsAssets.colors.gold,
    country: goodsAssets.countries.usa,
    os: goodsAssets.OS.ios,
    photo: 'https://content2.rozetka.com.ua/goods/images/big/221268401.jpg',
  },
];
